//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int ID { get; set; }
        public string HoLot { get; set; }
        public string Ten { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
